#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'sbt_serial_msg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 22

# The Active Message type associated with this message.
AM_TYPE = 102

class sbt_serial_msg(tinyos.message.Message.Message):
    # Create a new sbt_serial_msg of size 22.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=22):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <sbt_serial_msg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [telosb_temp=%f]\n" % (self.get_telosb_temp())
        except:
            pass
        try:
            s += "  [telosb_humid=%f]\n" % (self.get_telosb_humid())
        except:
            pass
        try:
            s += "  [telosb_light=%f]\n" % (self.get_telosb_light())
        except:
            pass
        try:
            s += "  [sbt_temp=%f]\n" % (self.get_sbt_temp())
        except:
            pass
        try:
            s += "  [sbt_light=%f]\n" % (self.get_sbt_light())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (True).
    #
    def isSigned_counter(self):
        return True
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: telosb_temp
    #   Field type: float
    #   Offset (bits): 16
    #   Size (bits): 32
    #

    #
    # Return whether the field 'telosb_temp' is signed (True).
    #
    def isSigned_telosb_temp(self):
        return True
    
    #
    # Return whether the field 'telosb_temp' is an array (False).
    #
    def isArray_telosb_temp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'telosb_temp'
    #
    def offset_telosb_temp(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'telosb_temp'
    #
    def offsetBits_telosb_temp(self):
        return 16
    
    #
    # Return the value (as a float) of the field 'telosb_temp'
    #
    def get_telosb_temp(self):
        return self.getFloatElement(self.offsetBits_telosb_temp(), 32, 0)
    
    #
    # Set the value of the field 'telosb_temp'
    #
    def set_telosb_temp(self, value):
        self.setFloatElement(self.offsetBits_telosb_temp(), 32, value, 0)
    
    #
    # Return the size, in bytes, of the field 'telosb_temp'
    #
    def size_telosb_temp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'telosb_temp'
    #
    def sizeBits_telosb_temp(self):
        return 32
    
    #
    # Accessor methods for field: telosb_humid
    #   Field type: float
    #   Offset (bits): 48
    #   Size (bits): 32
    #

    #
    # Return whether the field 'telosb_humid' is signed (True).
    #
    def isSigned_telosb_humid(self):
        return True
    
    #
    # Return whether the field 'telosb_humid' is an array (False).
    #
    def isArray_telosb_humid(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'telosb_humid'
    #
    def offset_telosb_humid(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'telosb_humid'
    #
    def offsetBits_telosb_humid(self):
        return 48
    
    #
    # Return the value (as a float) of the field 'telosb_humid'
    #
    def get_telosb_humid(self):
        return self.getFloatElement(self.offsetBits_telosb_humid(), 32, 0)
    
    #
    # Set the value of the field 'telosb_humid'
    #
    def set_telosb_humid(self, value):
        self.setFloatElement(self.offsetBits_telosb_humid(), 32, value, 0)
    
    #
    # Return the size, in bytes, of the field 'telosb_humid'
    #
    def size_telosb_humid(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'telosb_humid'
    #
    def sizeBits_telosb_humid(self):
        return 32
    
    #
    # Accessor methods for field: telosb_light
    #   Field type: float
    #   Offset (bits): 80
    #   Size (bits): 32
    #

    #
    # Return whether the field 'telosb_light' is signed (True).
    #
    def isSigned_telosb_light(self):
        return True
    
    #
    # Return whether the field 'telosb_light' is an array (False).
    #
    def isArray_telosb_light(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'telosb_light'
    #
    def offset_telosb_light(self):
        return (80 / 8)
    
    #
    # Return the offset (in bits) of the field 'telosb_light'
    #
    def offsetBits_telosb_light(self):
        return 80
    
    #
    # Return the value (as a float) of the field 'telosb_light'
    #
    def get_telosb_light(self):
        return self.getFloatElement(self.offsetBits_telosb_light(), 32, 0)
    
    #
    # Set the value of the field 'telosb_light'
    #
    def set_telosb_light(self, value):
        self.setFloatElement(self.offsetBits_telosb_light(), 32, value, 0)
    
    #
    # Return the size, in bytes, of the field 'telosb_light'
    #
    def size_telosb_light(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'telosb_light'
    #
    def sizeBits_telosb_light(self):
        return 32
    
    #
    # Accessor methods for field: sbt_temp
    #   Field type: float
    #   Offset (bits): 112
    #   Size (bits): 32
    #

    #
    # Return whether the field 'sbt_temp' is signed (True).
    #
    def isSigned_sbt_temp(self):
        return True
    
    #
    # Return whether the field 'sbt_temp' is an array (False).
    #
    def isArray_sbt_temp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sbt_temp'
    #
    def offset_sbt_temp(self):
        return (112 / 8)
    
    #
    # Return the offset (in bits) of the field 'sbt_temp'
    #
    def offsetBits_sbt_temp(self):
        return 112
    
    #
    # Return the value (as a float) of the field 'sbt_temp'
    #
    def get_sbt_temp(self):
        return self.getFloatElement(self.offsetBits_sbt_temp(), 32, 0)
    
    #
    # Set the value of the field 'sbt_temp'
    #
    def set_sbt_temp(self, value):
        self.setFloatElement(self.offsetBits_sbt_temp(), 32, value, 0)
    
    #
    # Return the size, in bytes, of the field 'sbt_temp'
    #
    def size_sbt_temp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'sbt_temp'
    #
    def sizeBits_sbt_temp(self):
        return 32
    
    #
    # Accessor methods for field: sbt_light
    #   Field type: float
    #   Offset (bits): 144
    #   Size (bits): 32
    #

    #
    # Return whether the field 'sbt_light' is signed (True).
    #
    def isSigned_sbt_light(self):
        return True
    
    #
    # Return whether the field 'sbt_light' is an array (False).
    #
    def isArray_sbt_light(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'sbt_light'
    #
    def offset_sbt_light(self):
        return (144 / 8)
    
    #
    # Return the offset (in bits) of the field 'sbt_light'
    #
    def offsetBits_sbt_light(self):
        return 144
    
    #
    # Return the value (as a float) of the field 'sbt_light'
    #
    def get_sbt_light(self):
        return self.getFloatElement(self.offsetBits_sbt_light(), 32, 0)
    
    #
    # Set the value of the field 'sbt_light'
    #
    def set_sbt_light(self, value):
        self.setFloatElement(self.offsetBits_sbt_light(), 32, value, 0)
    
    #
    # Return the size, in bytes, of the field 'sbt_light'
    #
    def size_sbt_light(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'sbt_light'
    #
    def sizeBits_sbt_light(self):
        return 32
    
